default:
  commands:
    - yum clean all
    - touch hello.txt
    - echo "test" > hello.txt
    - cat hello.txt
    - rm hello.txt
  packages:
    - vim
    - git
  package_install_command: "yum install -y"
