default:
  packages:
    - vim
    - git
    - postgresql
  files:
    -
      path: '/home/vagrant/README'
      content: >

        # This system is provisioned by Sokan

        # ===================================

