default:
  packages:
    - vim
    - git
    - postgresql
  package_install_cmd: "yum install -y"
  files:
    -
      path: '/home/vagrant/README'
      content: >

        # This system is provisioned by Sokan

        # ===================================

